#!/usr/bin/env node
var http = require('http');
var fs = require('fs');
var url = require('url');
var port = process.argv[2];

if (!port) {
	console.log('请指定一个端口');
	process.exit(1);
}

var server = http.createServer(function (request, response) {
	var parsedUrl = url.parse(request.url, true);
	var pathWithQuery = request.url;
	var queryString = '';
	if (pathWithQuery.indexOf('?') >= 0) {
		queryString = pathWithQuery.substring(pathWithQuery.indexOf('?'));
	}
	var path = parsedUrl.pathname;
	var query = parsedUrl.query;
	var method = request.method;

	//主要代码从此处开始

	console.log('含查询字符串的路径\n' + pathWithQuery);

	if (path === '/') {
		// 如果用户请求的是 / 路径
		var string = fs.readFileSync('./index.html', 'utf8');
		var amount = fs.readFileSync('./db', 'utf8');
		string = string.replace('&&&amount&&&', amount);
		response.setHeader('Content-Type', 'text/html;charset=utf-8');
		response.write(string);
		response.end();
	} else if (path === '/style.css') {
		var string = fs.readFileSync('./style.css', 'utf8');
		response.setHeader('Content-Type', 'text/css');
		response.write(string);
		response.end();
	} else if (path === '/main.js') {
		var string = fs.readFileSync('./main.js', 'utf8');
		response.setHeader('Content-Type', 'application/javascript');
		response.write(string);
		response.end();
	} else if (path === '/pay') {
		var amount = fs.readFileSync('./db', 'utf8');
		var newAmount = amount - 1;
		fs.writeFileSync('./db', newAmount);
		response.setHeader('Content-Type', 'application/javascript');
		response.statusCode = 200;
		response.write(`amount.innerText = amount.innerText - 1`);
		response.end();
	} else {
		response.statusCode = 404;
		response.setHeader('Content-Type', 'text/html;charset=utf-8');
		response.write('找不到对应的路径，你需要自行修改 server');
		response.end();
	}

	//主要代码从此处结束
	console.log(method + ' ' + request.url);
});

server.listen(port);
console.log('监听 ' + port + ' 成功，请在浏览器打开 http://localhost:' + port);
